# Postgres Database for Development
version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
volumes:
  pgdata:
